### ISSUE TITLE
Incorrect parsing of some lists

### ISSUE THREAD

**Issue by lorenzoiuri** [mrbaseman/parse_yaml#16] opened 2023-08-17 15:32 UTC
I've experienced an incorrect parsing of list items.

This yaml produces the variables below, in particular:
- `api_plan_keyless_resource_filtering_whitelist_1='path: /swagger'` 
whereas I expected 
- `api_plan_keyless_resource_filtering_whitelist_1_path=/swagger`

```yaml
api:
  name: be-dotnet-01
  add_env_prefix: false
  version: v1
  enabled: true
  plan:
    keyless:
      enabled: true
      resource_filtering:
        enable: true
        whitelist:
          - path: "/swagger"
            methods: ["GET", "PUT"]
    jwt:
      enabled: false
    apikey:
      enabled: false
```
```shell
...
api_plan_=' api_plan_keyless api_plan_jwt api_plan_apikey'
api_plan_keyless_=' api_plan_keyless_enabled api_plan_keyless_resource_filtering'
api_plan_keyless_enabled=true
api_plan_keyless_resource_filtering_=' api_plan_keyless_resource_filtering_enable api_plan_keyless_resource_filtering_whitelist'
api_plan_keyless_resource_filtering_enable=true
api_plan_keyless_resource_filtering_whitelist_=' api_plan_keyless_resource_filtering_whitelist_1'
api_plan_keyless_resource_filtering_whitelist_1='path: /swagger'
api_plan_keyless_resource_filtering_whitelist_1_=' api_plan_keyless_resource_filtering_whitelist_1_methods'
api_plan_keyless_resource_filtering_whitelist_1_methods_=' api_plan_keyless_resource_filtering_whitelist_1_methods_1 api_plan_keyless_resource_filtering_whitelist_1_methods_2'
api_plan_keyless_resource_filtering_whitelist_1_methods_1=GET
api_plan_keyless_resource_filtering_whitelist_1_methods_2=DELETE
...
```

The following yaml, instead, seems to be parsed fine:
```yaml
api:
  name: be-dotnet-01
  add_env_prefix: false
  version: v1
  enabled: true
  plan:
    keyless:
      enabled: true
      resource_filtering:
        enable: true
        whitelist:
          -
            path: "/swagger"
            methods: ["GET", "DELETE"]
    jwt:
      enabled: false
    apikey:
      enabled: false
```
```bash
...
api_plan_=' api_plan_keyless api_plan_jwt api_plan_apikey'
api_plan_keyless_=' api_plan_keyless_enabled api_plan_keyless_resource_filtering'
api_plan_keyless_enabled=true
api_plan_keyless_resource_filtering_=' api_plan_keyless_resource_filtering_enable api_plan_keyless_resource_filtering_whitelist'
api_plan_keyless_resource_filtering_enable=true
api_plan_keyless_resource_filtering_whitelist_=' api_plan_keyless_resource_filtering_whitelist_1'
api_plan_keyless_resource_filtering_whitelist_1_=' api_plan_keyless_resource_filtering_whitelist_1_path api_plan_keyless_resource_filtering_whitelist_1_methods'
api_plan_keyless_resource_filtering_whitelist_1_methods_=' api_plan_keyless_resource_filtering_whitelist_1_methods_1 api_plan_keyless_resource_filtering_whitelist_1_methods_2'
api_plan_keyless_resource_filtering_whitelist_1_methods_1=GET
api_plan_keyless_resource_filtering_whitelist_1_methods_2=DELETE
api_plan_keyless_resource_filtering_whitelist_1_path=/swagger
...
```

How I ran the script (in the bash shell):
- `source parse_yaml.sh`
- `eval $(parse_yaml api.yaml)`
- `set -o posix ; set | grep keyless`

**Comment by mrbaseman** [comment] 2023-09-21 20:31
Sorry, I can't reproduce this in Bash on Ubuntu, but it could be a platform dependent issue. What shell/OS are you using?

**Comment by lorenzoiuri** [comment] 2023-09-22 07:08
> Sorry, I can't reproduce this in Bash on Ubuntu, but it could be a platform dependent issue. What shell/OS are you using?

I'm using bash 5.1.16 on Ubuntu 22.04 on WSL.

**Comment by mrbaseman** [comment] 2023-09-22 19:32
Oh, I'm still on Ubuntu 20.04 with bash 5.0.17. I wouldn't expect breaking changes like this within one series of OSes. Hmm... I'm going to update one of my VMs. I should start to migrate my systems anyway. But well, maybe there are some more surprises. Anyhow, we'll see if I can reproduce it on Ubuntu 22.04.  It could as well be a choice of packages (one or another implementation of awk or something (I haven't looked that deep into the issue yet). But it's always easier to fix bugs when you can reproduce them at least.

**Comment by lorenzoiuri** [comment] 2023-09-23 15:56
Thank you. I repeated the test in an ubuntu 20.04 docker container and the problem is also present.

**Comment by mrbaseman** [comment] 2023-09-23 20:46
I'm really sorry. I don't know what I have done 2 days ago. Most probably I just didn't look closely enough at the output.
I think I have a fix for this issue  in [this branch](https://github.com/mrbaseman/parse_yaml/tree/16). 
Can you confirm that this fix works for you?

**Comment by lorenzoiuri** [comment] 2023-09-24 16:24
Yes, now it appears to work properly.
Thank you for the quick fix!

**Comment by mrbaseman** [comment] 2023-09-25 21:33
I have pushed the fix to the master branch and also added a test to the new test suite.

Quoting myself:
> I'm really sorry. I don't know what I have done 2 days ago. 
I think I have copied the working example into a local file to see how the output should look like and copied the reproducer into that file, but forgot to save it for the second run. I'm sorry about that.

**Closed by mrbaseman** 2023-09-25 21:33 UTC
